### ISSUE TITLE
Add image resize interpolation option

### ISSUE THREAD

**Issue by oziphantom** [wutipong/ZipPicViewUWP#3]
Hi, would you be able to add an option in the settings that allows me to choose the method is uses the scale the image up? For most things the Fant option is fine, but I also do a lot of pixel art projects so having something that expands the tiny sprites up to full screen so I can see them in great, but not so good in Fant, NearestNeighbor would be a real help.

**Comment by wutipong** [comment]
I'm sorry for taking so long. It's been a while since the last time I was updating the project.

This feature is now in the master branch and should be up in the next release.

**Comment by oziphantom** [comment]
No worries Mate, looking forward to it ;) Thank you.
